version: '3.8'

services:
  db:
    container_name: ordago_bdd
    image: "postgres"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=ordago
      - POSTGRES_USER=ordago
      - POSTGRES_PASSWORD=ordago
    env_file:
      - ./.env
    ports:
      - 5432:5432
    restart: always
    networks:
      - test-ordago
  api:
    container_name: ordago_api
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=ordago
      - POSTGRES_USER=ordago
      - POSTGRES_PASSWORD=ordago
    depends_on:
      - db
    restart: always
    networks:
      - test-ordago
networks:
  test-ordago:
